apiVersion: apps/v1
kind: Deployment
metadata:
  name: workshop-organizer-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workshop-organizer-db
  template:
    metadata:
      labels:
        app: workshop-organizer-db
    spec:
      containers:
      - name: workshop-organizer-db
        image: postgres:13
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: workshop-organizer-db-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: workshop-organizer-db-secret
              key: password
        - name: POSTGRES_DB
          value: workshop-organizer-database
        ports:
        - containerPort: 5432